---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite

- name: Install unzip server packages
  yum:
    name: unzip
    state: present
  tags: prerequisite

- name: Unarchive awscliv2.zip in /root
  unarchive:
    src: /home/centos/ansible-posqlpgpoolcl3/awscliv2.zip
    dest: /root
    owner: root
    group: root
    mode: '0755'
  tags: prerequisite

- name: Check if /usr/local/aws-cli exist - Exit if not
  stat:
    path: /usr/local/aws-cli
  register: foundedDir
  tags: prerequisite

- name: Thinking to do
  debug:
    msg: "Directory exist. Skipping installation"
  when: foundedDir.stat.isdir is defined
  tags: prerequisite

- name: Installing code
  shell: /root/aws/install
  when: foundedDir.stat.isdir is not defined
  become: yes
  tags: prerequisite

- name: Install LVM2
  yum:
    name: lvm2.x86_64
    state: present
  tags: prerequisite

- name: Add repository for PostgreSQL
  yum:
    name: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm
    state: present
  tags: prerequisite

- name: Install PostgreSQL server packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql11
    - postgresql11-server.x86_64
    - postgresql11-contrib.x86_64
    - postgresql11-devel.x86_64
    - postgresql11-libs.x86_64
    - postgresql11-plperl.x86_64
    - python-psycopg2
    state: present
  tags: prerequisite

- name: Add repository for PgPool II
  yum:
    name: http://www.pgpool.net/yum/rpms/4.1/redhat/rhel-7-x86_64/pgpool-II-release-4.1-1.noarch.rpm
    state: present
  tags: prerequisite

- name: Install PgPool II server packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - pgpool-II-pg11
    - pgpool-II-pg11-devel.x86_64
    - pgpool-II-pg11-extensions.x86_64
    - pgpool-II-pg11-debuginfo.x86_64
    state: present
  tags: prerequisite

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite
